<template>
  <div class="container">
    <h2
      style="
        margin-right: auto;
        margin-bottom: 2em;
        margin-left: auto;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: center;
        color: rgb(255, 255, 255);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 17.6px;
        font-weight: bold;
        display: table;
        padding-right: 0.2em;
        padding-left: 0.2em;
        background: rgb(15, 76, 129);
      "
      data-mpa-powered-by="yiban.io"
    >
      基础用法
      <mpchecktext
        contenteditable="false"
        id="1632667401853_0.5161689880660878"
      >
      </mpchecktext>
    </h2>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      点击新增标注按钮来创建一个新标注区域，点击进行绘制，双击结束，最终的数据以比例值返回。
      <mpchecktext
        contenteditable="false"
        id="1632667401854_0.5985071058669285"
      >
      </mpchecktext>
    </p>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      1.引入
      <code
        style="
          white-space: pre-wrap;
          -webkit-tap-highlight-color: transparent;
          color: rgb(221, 17, 68);
          line-height: 1.75;
          font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
            'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
            'Microsoft YaHei', Arial, sans-serif;
          font-size: 14.4px;
          background: rgba(27, 31, 35, 0.05);
          padding: 3px 5px;
          border-radius: 4px;
        "
        >markjs</code
      >，再按需引入你需要的插件，因为文档框架限制，所以所有示例都一次性引入所有内置插件。
      <mpchecktext
        contenteditable="false"
        id="1632667401855_0.5624463050190933"
      >
      </mpchecktext>
    </p>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      2.创建一个容器元素，容器元素需要有固定的宽高。
      <mpchecktext
        contenteditable="false"
        id="1632667401856_0.33275726618767076"
      >
      </mpchecktext>
    </p>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      3.创建一个实例，传入特定的配置项，之后再调用特定的功能方法即可。
      <mpchecktext
        contenteditable="false"
        id="1632667401857_0.8283033440096883"
      >
      </mpchecktext>
    </p>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      同时这个示例也演示了鼠标样式插件的功能，就是在特定的情况下显示特定的鼠标指针及提示信息，如果你不需要可以不引入，需要定制也可以自己开发对应的插件。
      <mpchecktext
        contenteditable="false"
        id="1632667401858_0.3584219044531489"
      >
      </mpchecktext>
    </p>
    <section
      class="code-snippet__github"
      style="
        margin: 10px 8px;
        -webkit-tap-highlight-color: transparent;
        display: flex;
        font-size: 12px;
        position: relative;
        height: auto;
        background-color: rgb(247, 247, 247);
        border-radius: 8px;
        color: rgb(0, 0, 0);
        font-family: 'PingFang SC';
        text-align: start;
        white-space: normal;
      "
    >
      <pre
        class="code__pre"
        data-lang="vue"
        style="
          -webkit-tap-highlight-color: transparent;
          display: grid;
          position: relative;
          counter-reset: line 0;
          overflow-x: auto;
          padding: 1em;
          -webkit-box-flex: 1;
          flex: 1 1 0%;
          line-height: 20px;
          font-family: 'Operator Mono', Consolas, Monaco, Menlo, monospace;
        "
      >
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;template&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;div</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">class</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"container"</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;div</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">class</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"markBox"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">ref</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"markBox1"</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;&lt;/div&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      type</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"primary"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">@click</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"create1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">disabled</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"!editing1 || !!curEditMarkItem1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;新增标注&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" @click="exit1" :disabled="!isCreateMarking1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;退出新增&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" @click="getMarkData1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;获取标注（控制台查看）&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      type</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"primary"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      icon</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"el-icon-delete"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">@click</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"deleteItem1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">disabled</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"!curEditMarkItem1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" icon="el-icon-delete" @click="deleteAll1"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;删除全部&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/div&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/template&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;script&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">import</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">from</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"@wanglin1994/markjs"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">let</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> mark1 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">null</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">export</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">default</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  data</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">return</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 基础用法</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      editing1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      curEditMarkItem1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">null</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      isCreateMarking1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">false</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">};</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  mounted</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    setTimeout</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 基础用法</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">new</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">({</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">$refs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">markBox1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        hoverActive</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"CURRENT-MARK-ITEM-CHANGE"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">item</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">curEditMarkItem1 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> item</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"IS-CREATE-MARKING-CHANGE"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">isCreateMarking1 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"NOT-ENOUGH-END-POINTS"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">$message</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">warning</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"至少需要绘制三个端点"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  methods</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 基础用法</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    getMarkData1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      console</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">log</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">getMarkData</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(),</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> JSON</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">stringify</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">getMarkData</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()));</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    deleteItem1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">deleteMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">curEditMarkItem1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    deleteAll1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">deleteAllMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    create1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">createMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    exit1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark1</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">exitCreate</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">};</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/script&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;style</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">lang</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"less"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">scoped</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">container </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  width</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">100</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">%;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">markBox </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    width</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">100</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">%;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    height</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">400px</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    background</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">color</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">#f5f5f5;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    margin</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">bottom</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">10px</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">}</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">}</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/style&gt;<mpchecktext contenteditable="false" id="1632667401859_0.9140972372992491">
</mpchecktext></span></span></code>
</pre>
    </section>

    <div class="markBox" ref="markBox1"></div>
    <el-button
      type="primary"
      @click="create1"
      :disabled="!editing1 || !!curEditMarkItem1"
      >新增标注</el-button
    >
    <el-button type="primary" @click="exit1" :disabled="!isCreateMarking1"
      >退出新增</el-button
    >
    <el-button type="primary" @click="getMarkData1"
      >获取标注（控制台查看）</el-button
    >
    <el-button
      type="primary"
      icon="el-icon-delete"
      @click="deleteItem1"
      :disabled="!curEditMarkItem1"
    ></el-button>
    <el-button type="primary" icon="el-icon-delete" @click="deleteAll1"
      >删除全部</el-button
    >
  </div>
</template>

<script>
import Markjs from "@wanglin1994/markjs";

let mark1 = null;
export default {
  data() {
    return {
      // 基础用法
      editing1: true,
      curEditMarkItem1: null,
      isCreateMarking1: false,
    };
  },
  mounted() {
    setTimeout(() => {
      // 基础用法
      mark1 = new Markjs({
        el: this.$refs.markBox1,
        hoverActive: true,
      });
      mark1.on("CURRENT-MARK-ITEM-CHANGE", (item) => {
        this.curEditMarkItem1 = item;
      });
      mark1.on("IS-CREATE-MARKING-CHANGE", (state) => {
        this.isCreateMarking1 = state;
      });
      mark1.on("NOT-ENOUGH-END-POINTS", (state) => {
        this.$message.warning("至少需要绘制三个端点");
      });
    });
  },
  methods: {
    // 基础用法
    getMarkData1() {
      console.log(mark1.getMarkData(), JSON.stringify(mark1.getMarkData()));
    },
    deleteItem1() {
      mark1.deleteMarkItem(this.curEditMarkItem1);
    },
    deleteAll1() {
      mark1.deleteAllMarkItem();
    },
    create1() {
      mark1.createMarkItem();
    },
    exit1() {
      mark1.exitCreate();
    },
  },
};
</script>

<style lang="less" scoped>
.container {
  width: 100%;

  .markBox {
    width: 100%;
    height: 400px;
    background-color: #f5f5f5;
    margin-bottom: 10px;
  }
}
</style>