<template>
  <div class="container">
    <h2
      style="
        margin-right: auto;
        margin-bottom: 2em;
        margin-left: auto;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: center;
        color: rgb(255, 255, 255);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 17.6px;
        font-weight: bold;
        display: table;
        padding-right: 0.2em;
        padding-left: 0.2em;
        background: rgb(15, 76, 129);
      "
      data-mpa-powered-by="yiban.io"
    >
      单独编辑
      <mpchecktext
        contenteditable="false"
        id="1632667401870_0.5802321139124798"
      >
      </mpchecktext>
    </h2>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      默认情况下激活某个区域进行标注时其他非激活标注仍然会存在，可以通过设置属性
      <code
        style="
          white-space: pre-wrap;
          -webkit-tap-highlight-color: transparent;
          color: rgb(221, 17, 68);
          line-height: 1.75;
          font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
            'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
            'Microsoft YaHei', Arial, sans-serif;
          font-size: 14.4px;
          background: rgba(27, 31, 35, 0.05);
          padding: 3px 5px;
          border-radius: 4px;
        "
        >single</code
      >为
      <code
        style="
          white-space: pre-wrap;
          -webkit-tap-highlight-color: transparent;
          color: rgb(221, 17, 68);
          line-height: 1.75;
          font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
            'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
            'Microsoft YaHei', Arial, sans-serif;
          font-size: 14.4px;
          background: rgba(27, 31, 35, 0.05);
          padding: 3px 5px;
          border-radius: 4px;
        "
        >true</code
      >来控制只显示激活的那个标注区域。
      <mpchecktext contenteditable="false" id="1632667401871_0.89205054109877">
      </mpchecktext>
    </p>
    <section
      class="code-snippet__github"
      style="
        margin: 10px 8px;
        -webkit-tap-highlight-color: transparent;
        display: flex;
        font-size: 12px;
        position: relative;
        height: auto;
        background-color: rgb(247, 247, 247);
        border-radius: 8px;
        color: rgb(0, 0, 0);
        font-family: 'PingFang SC';
        text-align: start;
        white-space: normal;
      "
    >
      <pre
        class="code__pre"
        data-lang="vue"
        style="
          -webkit-tap-highlight-color: transparent;
          display: grid;
          position: relative;
          counter-reset: line 0;
          overflow-x: auto;
          padding: 1em;
          -webkit-box-flex: 1;
          flex: 1 1 0%;
          line-height: 20px;
          font-family: 'Operator Mono', Consolas, Monaco, Menlo, monospace;
        "
      >
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;template&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;div</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">class</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"container"</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;div</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">class</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"markBox"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">ref</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"markBox4"</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;&lt;/div&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      type</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"primary"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">@click</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"create4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">disabled</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"!editing4 || !!curEditMarkItem4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;新增标注&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" @click="exit4" :disabled="!isCreateMarking4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;退出新增&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" @click="getMarkData4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;获取标注（控制台查看）&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      type</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"primary"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      icon</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"el-icon-delete"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">@click</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"deleteItem4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">disabled</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"!curEditMarkItem4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" icon="el-icon-delete" @click="deleteAll4"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;删除全部&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/div&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/template&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;script&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">import</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">from</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"@wanglin1994/markjs"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">import</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> mousePlugin </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">from</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"@wanglin1994/markjs/src/plugins/mouse"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">use</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mousePlugin</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">let</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> mark4 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">null</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">export</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">default</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  data</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">return</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 单独编辑</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      editing4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      curEditMarkItem4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">null</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      isCreateMarking4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">false</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">};</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  mounted</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    setTimeout</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 单独编辑</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">new</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">({</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">$refs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">markBox4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        hoverActive</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        single</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"CURRENT-MARK-ITEM-CHANGE"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">item</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">curEditMarkItem4 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> item</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"IS-CREATE-MARKING-CHANGE"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">isCreateMarking4 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"NOT-ENOUGH-END-POINTS"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">$message</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">warning</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"至少需要绘制三个端点"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  methods</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    getMarkData4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      console</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">log</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">getMarkData</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(),</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> JSON</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">stringify</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">getMarkData</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()));</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    deleteItem4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">deleteMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">curEditMarkItem4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    deleteAll4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">deleteAllMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    create4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">createMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    exit4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark4</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">exitCreate</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">};</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/script&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;style</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">lang</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"less"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">scoped</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">container </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  width</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">100</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">%;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">markBox </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    width</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">100</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">%;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    height</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">400px</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    background</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">color</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">#f5f5f5;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    margin</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">bottom</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">10px</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">}</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">}</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/style&gt;<mpchecktext contenteditable="false" id="1632667401872_0.5371462075657598">
</mpchecktext></span></span></code>
</pre>
    </section>

    <div class="markBox" ref="markBox4"></div>
    <el-button
      type="primary"
      @click="create4"
      :disabled="!editing4 || !!curEditMarkItem4"
      >新增标注</el-button
    >
    <el-button type="primary" @click="exit4" :disabled="!isCreateMarking4"
      >退出新增</el-button
    >
    <el-button type="primary" @click="getMarkData4"
      >获取标注（控制台查看）</el-button
    >
    <el-button
      type="primary"
      icon="el-icon-delete"
      @click="deleteItem4"
      :disabled="!curEditMarkItem4"
    ></el-button>
    <el-button type="primary" icon="el-icon-delete" @click="deleteAll4"
      >删除全部</el-button
    >
  </div>
</template>

<script>
import Markjs from "@wanglin1994/markjs";
import mousePlugin from "@wanglin1994/markjs/src/plugins/mouse";
Markjs.use(mousePlugin);

let mark4 = null;
export default {
  data() {
    return {
      // 单独编辑
      editing4: true,
      curEditMarkItem4: null,
      isCreateMarking4: false,
    };
  },
  mounted() {
    setTimeout(() => {
      // 单独编辑
      mark4 = new Markjs({
        el: this.$refs.markBox4,
        hoverActive: true,
        single: true,
      });
      mark4.on("CURRENT-MARK-ITEM-CHANGE", (item) => {
        this.curEditMarkItem4 = item;
      });
      mark4.on("IS-CREATE-MARKING-CHANGE", (state) => {
        this.isCreateMarking4 = state;
      });
      mark4.on("NOT-ENOUGH-END-POINTS", (state) => {
        this.$message.warning("至少需要绘制三个端点");
      });
    });
  },
  methods: {
    getMarkData4() {
      console.log(mark4.getMarkData(), JSON.stringify(mark4.getMarkData()));
    },
    deleteItem4() {
      mark4.deleteMarkItem(this.curEditMarkItem4);
    },
    deleteAll4() {
      mark4.deleteAllMarkItem();
    },
    create4() {
      mark4.createMarkItem();
    },
    exit4() {
      mark4.exitCreate();
    },
  },
};
</script>

<style lang="less" scoped>
.container {
  width: 100%;

  .markBox {
    width: 100%;
    height: 400px;
    background-color: #f5f5f5;
    margin-bottom: 10px;
  }
}
</style>