<template>
  <div class="container" ref="container">
    <h2
      style="
        margin-right: auto;
        margin-bottom: 2em;
        margin-left: auto;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: center;
        color: rgb(255, 255, 255);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 17.6px;
        font-weight: bold;
        display: table;
        padding-right: 0.2em;
        padding-left: 0.2em;
        background: rgb(15, 76, 129);
      "
      data-mpa-powered-by="yiban.io"
    >
      特定形状
      <mpchecktext
        contenteditable="false"
        id="1632667401866_0.7225950428735319"
      >
      </mpchecktext>
    </h2>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      有时候可能需要限制特定的形状，这可以通过
      <code
        style="
          white-space: pre-wrap;
          -webkit-tap-highlight-color: transparent;
          color: rgb(221, 17, 68);
          line-height: 1.75;
          font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
            'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
            'Microsoft YaHei', Arial, sans-serif;
          font-size: 14.4px;
          background: rgba(27, 31, 35, 0.05);
          padding: 3px 5px;
          border-radius: 4px;
        "
        >shape</code
      >插件来实现，因为本人水平所限，只内置了正方形一种形状，你可以通过该插件来扩展你需要的形状支持。
      <mpchecktext
        contenteditable="false"
        id="1632667401867_0.8515602552847328"
      >
      </mpchecktext>
    </p>
    <p
      style="
        margin: 1.5em 8px;
        -webkit-tap-highlight-color: transparent;
        white-space: normal;
        text-align: left;
        color: rgb(63, 63, 63);
        line-height: 1.75;
        font-family: -apple-system-font, BlinkMacSystemFont, 'Helvetica Neue',
          'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei UI',
          'Microsoft YaHei', Arial, sans-serif;
        font-size: 16px;
        letter-spacing: 0.1em;
      "
    >
      同时本示例也演示了在创建新标注时可通过第二个参数传入配置项，定义填充颜色等。
      <mpchecktext
        contenteditable="false"
        id="1632667401868_0.8624376942400467"
      >
      </mpchecktext>
    </p>
    <section
      class="code-snippet__github"
      style="
        margin: 10px 8px;
        -webkit-tap-highlight-color: transparent;
        display: flex;
        font-size: 12px;
        position: relative;
        height: auto;
        background-color: rgb(247, 247, 247);
        border-radius: 8px;
        color: rgb(0, 0, 0);
        font-family: 'PingFang SC';
        text-align: start;
        white-space: normal;
      "
    >
      <pre
        class="code__pre"
        data-lang="vue"
        style="
          -webkit-tap-highlight-color: transparent;
          display: grid;
          position: relative;
          counter-reset: line 0;
          overflow-x: auto;
          padding: 1em;
          -webkit-box-flex: 1;
          flex: 1 1 0%;
          line-height: 20px;
          font-family: 'Operator Mono', Consolas, Monaco, Menlo, monospace;
        "
      >
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;template&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;div</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">class</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"container"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">ref</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"container"</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;div</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">class</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"markBox"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">ref</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"markBox3"</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;&lt;/div&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      type</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"primary"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">@click</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"createShape3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">disabled</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"!editing3 || !!curEditMarkItem3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;创建形状&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" @click="exit3" :disabled="!isCreateMarking3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;退出新增&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" @click="getMarkData3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;获取标注（控制台查看）&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      type</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"primary"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      icon</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"el-icon-delete"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">@click</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"deleteItem3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">disabled</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"!curEditMarkItem3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    &lt;el-button type="primary" icon="el-icon-delete" @click="deleteAll3"</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;删除全部&lt;/</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">button</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/div&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/template&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;script&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">import</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">from</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"@wanglin1994/markjs"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">import</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> shapePlugin </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">from</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"@wanglin1994/markjs/src/plugins/shape"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">use</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">shapePlugin</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">let</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> mark3 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">null</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">export</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">default</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  data</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">return</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 特定形状</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      editing3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      curEditMarkItem3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">null</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      isCreateMarking3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">false</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">};</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  mounted</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    setTimeout</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 特定形状</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">new</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="typ" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">Markjs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">({</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        el</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">$refs</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">markBox3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        hoverActive</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">true</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"CURRENT-MARK-ITEM-CHANGE"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">item</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">curEditMarkItem3 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> item</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"IS-CREATE-MARKING-CHANGE"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">isCreateMarking3 </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">on</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"NOT-ENOUGH-END-POINTS"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">state</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">)</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=&gt;</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        </span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">$message</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">warning</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"至少需要绘制三个端点"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  methods</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">// 特定形状</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    getMarkData3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      console</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">log</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">getMarkData</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(),</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> JSON</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">stringify</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">getMarkData</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()));</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    deleteItem3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">deleteMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="kwd" style="-webkit-tap-highlight-color: transparent; color: rgb(167, 29, 93);">this</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">curEditMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">);</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    deleteAll3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">deleteAllMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    exit3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">exitCreate</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">();</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    createShape3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">()</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      mark3</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">createShapeMarkItem</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">(</span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"square"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">        fillColor</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="str" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"rgba(250,50,57,0.30)"</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">,</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">      </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">});</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">},</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">};</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/script&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;style</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">lang</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">=</span><span class="atv" style="-webkit-tap-highlight-color: transparent; color: rgb(24, 54, 145);">"less"</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="atn" style="-webkit-tap-highlight-color: transparent; color: rgb(121, 93, 163);">scoped</span><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&gt;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">container </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  width</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">100</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">%;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">.</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">markBox </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">{</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    width</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">100</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">%;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    height</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">400px</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    background</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">color</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="com" style="-webkit-tap-highlight-color: transparent; color: rgb(150, 152, 150);">#f5f5f5;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">    margin</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">-</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">bottom</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">:</span><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);"> </span><span class="lit" style="-webkit-tap-highlight-color: transparent; color: rgb(0, 134, 179);">10px</span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">;</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pln" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">  </span><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">}</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="pun" style="-webkit-tap-highlight-color: transparent; color: rgb(51, 51, 51);">}</span></span></code>
<code class="prettyprint prettyprinted" style="-webkit-tap-highlight-color: transparent; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; display: flex; position: relative; padding-right: 8px; border-width: 0px !important; border-style: initial !important; border-color: initial !important;"><span class="code-snippet_outer" style="-webkit-tap-highlight-color: transparent;"><span class="tag" style="-webkit-tap-highlight-color: transparent; color: navy;">&lt;/style&gt;<mpchecktext contenteditable="false" id="1632667401869_0.4302140972975885">
</mpchecktext></span></span></code>
</pre>
    </section>
    
    <div class="markBox" ref="markBox3"></div>
    <el-button
      type="primary"
      @click="createShape3"
      :disabled="!editing3 || !!curEditMarkItem3"
      >创建形状</el-button
    >
    <el-button type="primary" @click="exit3" :disabled="!isCreateMarking3"
      >退出新增</el-button
    >
    <el-button type="primary" @click="getMarkData3"
      >获取标注（控制台查看）</el-button
    >
    <el-button
      type="primary"
      icon="el-icon-delete"
      @click="deleteItem3"
      :disabled="!curEditMarkItem3"
    ></el-button>
    <el-button type="primary" icon="el-icon-delete" @click="deleteAll3"
      >删除全部</el-button
    >
  </div>
</template>

<script>
import Markjs from "@wanglin1994/markjs";
import shapePlugin from "@wanglin1994/markjs/src/plugins/shape";
Markjs.use(shapePlugin);

let mark3 = null;
export default {
  data() {
    return {
      // 特定形状
      editing3: true,
      curEditMarkItem3: null,
      isCreateMarking3: false,
    };
  },
  mounted() {
    setTimeout(() => {
      // 特定形状
      mark3 = new Markjs({
        el: this.$refs.markBox3,
        hoverActive: true,
      });
      mark3.on("CURRENT-MARK-ITEM-CHANGE", (item) => {
        this.curEditMarkItem3 = item;
      });
      mark3.on("IS-CREATE-MARKING-CHANGE", (state) => {
        this.isCreateMarking3 = state;
      });
      mark3.on("NOT-ENOUGH-END-POINTS", (state) => {
        this.$message.warning("至少需要绘制三个端点");
      });
    });
  },
  methods: {
    // 特定形状
    getMarkData3() {
      console.log(mark3.getMarkData(), JSON.stringify(mark3.getMarkData()));
    },
    deleteItem3() {
      mark3.deleteMarkItem(this.curEditMarkItem);
    },
    deleteAll3() {
      mark3.deleteAllMarkItem();
    },
    exit3() {
      mark3.exitCreate();
    },
    createShape3() {
      mark3.createShapeMarkItem("square", {
        fillColor: "rgba(250,50,57,0.30)",
      });
    },
  },
};
</script>

<style lang="less" scoped>
.container {
  width: 100%;

  .markBox {
    width: 100%;
    height: 400px;
    background-color: #f5f5f5;
    margin-bottom: 10px;
  }
}
</style>